package com.chubb.claims.events;

public enum ClaimEventType {
    CLAIM_SUBMITTED, CLAIM_ASSIGNED, CLAIM_REASSIGNED, INFO_REQUESTED, INFO_PROVIDED,
    CLAIM_ASSESSED, CLAIM_APPROVED, CLAIM_REJECTED, CLAIM_SETTLED
}
