CREATE TABLE claims (
    id                  UUID PRIMARY KEY,
    claim_number        VARCHAR(40)  NOT NULL UNIQUE,
    market              VARCHAR(5)   NOT NULL,
    claim_type          VARCHAR(20)  NOT NULL,
    status              VARCHAR(20)  NOT NULL,
    claimant_name       VARCHAR(200) NOT NULL,
    claimant_email      VARCHAR(200) NOT NULL,
    description         VARCHAR(4000) NOT NULL,
    incident_date       DATE         NOT NULL,
    currency            VARCHAR(3)   NOT NULL,
    estimated_amount    NUMERIC(15,2) NOT NULL,
    assessed_amount     NUMERIC(15,2),
    assigned_officer_id VARCHAR(100),
    rejection_reason    VARCHAR(1000),
    submitted_at        TIMESTAMP    NOT NULL,
    closed_at           TIMESTAMP,
    version             BIGINT       NOT NULL
);

-- Officer workload: "my open claims by status"
CREATE INDEX idx_claims_officer_status ON claims (assigned_officer_id, status);
-- Intake queue: unassigned claims per market/type, oldest first
CREATE INDEX idx_claims_status_market ON claims (status, market, claim_type, submitted_at);
-- Claimant tracking
CREATE INDEX idx_claims_claimant_email ON claims (claimant_email);

CREATE TABLE info_requests (
    id           UUID PRIMARY KEY,
    claim_id     UUID NOT NULL REFERENCES claims (id),
    question     VARCHAR(2000) NOT NULL,
    requested_by VARCHAR(100)  NOT NULL,
    requested_at TIMESTAMP     NOT NULL,
    response     VARCHAR(4000),
    responded_at TIMESTAMP
);
CREATE INDEX idx_info_requests_claim ON info_requests (claim_id);

CREATE TABLE claim_history (
    id          UUID PRIMARY KEY,
    claim_id    UUID NOT NULL REFERENCES claims (id),
    from_status VARCHAR(20),
    to_status   VARCHAR(20) NOT NULL,
    actor       VARCHAR(200) NOT NULL,
    note        VARCHAR(2000),
    occurred_at TIMESTAMP NOT NULL
);
CREATE INDEX idx_claim_history_claim ON claim_history (claim_id, occurred_at);

-- Transactional outbox: written in the same transaction as the state change, relayed to Kafka.
CREATE TABLE outbox_events (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_id UUID NOT NULL,
    payload      TEXT NOT NULL,
    created_at   TIMESTAMP NOT NULL,
    published_at TIMESTAMP
);
CREATE INDEX idx_outbox_unpublished ON outbox_events (published_at, id);
